ARG ROCM_BASE_IMAGE=scratch
FROM ${ROCM_BASE_IMAGE} AS llama_dl

ARG LLAMACPP_BUILD
ARG LLAMACPP_BOOSTS

ADD --keep-git-dir https://github.com/ggml-org/llama.cpp.git#${LLAMACPP_BUILD} /usr/src/llama.cpp
ADD --keep-git-dir https://github.com/stew675/llama-cpp-rdna-boosts.git#${LLAMACPP_BOOSTS} /usr/src/llama-cpp-rdna-boosts

FROM llama_dl AS llama_build

ARG AMDGPU_TARGET
ENV AMDGPU_TARGET=${AMDGPU_TARGET}

RUN git config --global user.name "Docker Build" && \
    git config --global user.email "buildenv@example.com"

ADD build-llama.sh /usr/src/
RUN /bin/bash -c "cd /usr/src; ./llama-cpp-rdna-boosts/scripts/apply-all.sh /usr/src/llama.cpp /usr/src/llama-cpp-rdna-boosts"
RUN /bin/bash -c "cd /usr/src; ./build-llama.sh"

FROM llama_build AS llama
ENV HF_HUB_CACHE=/mnt/hub
RUN mkdir /mnt/hub
