FROM ubuntu:26.04 AS initial_os

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  curl \
  git \
  gpg \
  libatomic1 \
  libquadmath0 \
  npm \
  perl \
  pip \
  python3.14-venv \
  wget

FROM initial_os AS rocm

ADD rocm-apt.gpg /etc/apt/keyrings/amdrocm.gpg
ADD rocm-apt.sources /etc/apt/sources.list.d/amdrocm-stable.sources

ARG AMDGPU_TARGET

RUN apt-get update && apt-get -y install \
  amdrocm10.0-$AMDGPU_TARGET \
  amdrocm-core-sdk10.0-$AMDGPU_TARGET

ADD rocm.ld.conf /etc/ld.so.conf.d/rocm.conf
RUN ldconfig
