ARG ROCM_BASE_IMAGE=scratch
FROM ${ROCM_BASE_IMAGE} AS llama_dl

ARG LLAMACPP_BUILD

ADD --unpack=true https://github.com/ggml-org/llama.cpp/archive/refs/tags/$LLAMACPP_BUILD.tar.gz /usr/src/
RUN mv /usr/src/llama.cpp-$LLAMACPP_BUILD /usr/src/llama.cpp

FROM llama_dl AS llama_build

ARG AMDGPU_TARGET
ENV AMDGPU_TARGET=${AMDGPU_TARGET}

ADD build-llama.sh /usr/src/
RUN /bin/bash -c "cd /usr/src; ./build-llama.sh"

FROM llama_build AS llama
ENV HF_HUB_CACHE=/mnt/hub
RUN mkdir /mnt/hub
